<?php

namespace App\Modules\Frontend\Database\Seeders;

use App\Modules\Frontend\Models\FrontendSection;
use App\Modules\Frontend\Services\FrontendSectionService;
use Illuminate\Database\Seeder;

class FrontendSectionSeeder extends Seeder
{
    public function run(): void
    {
        /** @var FrontendSectionService $service */
        $service = app(FrontendSectionService::class);

        $sections = [
            [
                'name' => 'Global Footer',
                'slug' => 'global-footer',
                'type' => 'footer',
                'status' => 'published',
                'description' => 'Reusable footer content.',
                'data' => [],
            ],
            [
                'name' => 'About Content',
                'slug' => 'about-rich-content',
                'type' => 'rich_content',
                'status' => 'published',
                'description' => 'Long-form content for the about page.',
                'data' => [
                    'title' => 'About this frontend stack',
                    'content' => '<p>This shared-content frontend stack is designed so you can add more themes later without redoing your content model.</p>',
                ],
            ],
            [
                'name' => 'Homepage Hero',
                'slug' => 'homepage-hero-leadatlas',
                'type' => 'homepage_hero',
                'status' => 'published',
                'description' => 'Map-driven hero for the LeadAtlas homepage.',
                'data' => [
                    'proof_count' => '128M',
                    'proof_countries' => '190',
                    'proof_text' => 'businesses indexed across :countries countries',
                    'title' => 'Every business on the map.',
                    'title_secondary' => 'Ranked before you call.',
                    'subtitle' => 'Search Google Maps by keyword and location. LeadAtlas pulls every matching business, finds who to contact, and scores how worth your time each one is.',
                    'primary_button_text' => 'Start finding leads',
                    'primary_button_link' => '/register',
                    'secondary_button_text' => 'See how scoring works',
                    'secondary_button_link' => '#features',
                    'screenshot_caption' => 'app.leadatlas.com/dashboard',
                    'screenshot_image' => null,
                    'screenshot_alt' => 'The LeadAtlas dashboard: two searches running, 1,284 leads found, and the highest-scoring businesses ranked by AI score.',
                    'lead_card_label' => 'AI analysis',
                    'lead_card_name' => 'Barton Springs Dental',
                    'lead_card_summary' => 'Busy practice, no online booking, ageing site. Strong fit for scheduling software.',
                    'lead_card_score' => 92,
                ],
            ],
            [
                'name' => 'Homepage Stages',
                'slug' => 'homepage-stages',
                'type' => 'homepage_stages',
                'status' => 'published',
                'description' => 'The funnel/run section for the LeadAtlas homepage.',
                'data' => [
                    'eyebrow' => 'The run',
                    'title' => 'You search once. The list gets shorter four times.',
                    'subtitle' => 'Every stage throws work away — that is the point. What reaches you is the remainder worth a phone call.',
                    'stages' => [
                        ['count' => '128', 'label' => 'plotted', 'variant' => 'find', 'description' => 'Every dentist Google Maps knows about within your radius — pulled with address, hours, and rating.'],
                        ['count' => '94', 'label' => 'contactable', 'variant' => 'find', 'description' => 'We follow each listing to its site and find an inbox and a direct line. Thirty-four had neither.'],
                        ['count' => '31', 'label' => 'scored 70+', 'variant' => 'ai', 'description' => 'The model reads reviews, booking flow, and site age, then rates how much your service is worth to them.'],
                        ['count' => '12', 'label' => 'worth calling', 'variant' => 'act', 'description' => 'Ranked, deduped against anyone you have already contacted, and ready to export.'],
                    ],
                    'callout_label' => 'Top of the twelve',
                    'callout_name' => 'Barton Springs Dental',
                    'callout_score' => 92,
                    'callout_text' => 'no way to book online',
                ],
            ],
            [
                'name' => 'Homepage Features',
                'slug' => 'homepage-features-leadatlas',
                'type' => 'homepage_features',
                'status' => 'published',
                'description' => 'Feature grid for the LeadAtlas homepage.',
                'data' => [
                    'eyebrow' => 'What you get',
                    'title' => 'Everything between a map pin and a signed deal.',
                    'subtitle' => 'Discovery, enrichment, scoring, and outreach in one place — so the list you export is already ranked and already contactable.',
                    'items' => [
                        ['icon' => 'ph-map-trifold', 'variant' => 'find', 'title' => 'Google Maps discovery', 'description' => 'Search any keyword and location and pull every matching business — not the first page, the whole result set.', 'meta' => '128M businesses indexed'],
                        ['icon' => 'ph-address-book', 'variant' => 'find', 'title' => 'Contact enrichment', 'description' => 'We follow each listing to its website and pull the email, phone, and social profiles the listing itself never shows.', 'meta' => 'Email · phone · socials'],
                        ['icon' => 'ph-gauge', 'variant' => 'ai', 'title' => 'AI lead scoring', 'description' => 'Reviews, site quality, and booking setup become one number from 0–100, with the reasoning written out.', 'meta' => 'Scored on every search'],
                        ['icon' => 'ph-sparkle', 'variant' => 'ai', 'title' => 'AI analysis & outreach', 'description' => 'A written summary of what each business is missing, and a first email drafted around exactly that gap.', 'meta' => 'Summary · draft email'],
                        ['icon' => 'ph-kanban', 'variant' => 'act', 'title' => 'Built-in CRM pipeline', 'description' => 'Move leads through stages, tag them, log calls and notes. No second tool and no exporting just to stay organised.', 'meta' => 'Stages · tags · activity'],
                        ['icon' => 'ph-download-simple', 'variant' => 'act', 'title' => 'Export & API', 'description' => 'Send the ranked list to CSV, your own CRM, or an email campaign — or pull it straight out over the API.', 'meta' => 'CSV · webhook · REST'],
                    ],
                ],
            ],
            [
                'name' => 'Homepage Voices',
                'slug' => 'homepage-voices',
                'type' => 'homepage_voices',
                'status' => 'published',
                'description' => 'Testimonial carousel for the LeadAtlas homepage.',
                'data' => [
                    'eyebrow' => 'Who uses it',
                    'title' => 'Built for people who sell to local business.',
                    'subtitle' => 'Agencies, freelancers, and sales teams who were doing this by hand in a spreadsheet.',
                    'items' => [
                        ['variant' => 'find', 'icon' => 'ph-map-trifold', 'label' => 'On finding leads', 'quote' => 'We used to burn a full day a week copying business details off Maps into a sheet. Now one search does the same thing before the coffee is cold.', 'avatar' => null, 'name' => 'Rachel Mendez', 'role' => 'Founder, Northgate Digital'],
                        ['variant' => 'ai', 'icon' => 'ph-sparkle', 'label' => 'On the scoring', 'quote' => 'The score is only useful because it shows its reasoning. I can see it flagged a practice for having no booking system, and I know that is a real conversation to have.', 'avatar' => null, 'name' => 'Daniel Okafor', 'role' => 'Sales lead, Certa Group'],
                        ['variant' => 'act', 'icon' => 'ph-paper-plane-tilt', 'label' => 'On the outreach', 'quote' => 'I rewrite maybe a third of the drafted emails. The other two thirds go out as written, and they mention something specific about the business — which is why they get answered.', 'avatar' => null, 'name' => 'Sofia Kallio', 'role' => 'Freelance consultant'],
                        ['variant' => 'find', 'icon' => 'ph-map-trifold', 'label' => 'On the search', 'quote' => 'Searching costs nothing, so I check a new town before I decide whether it is worth working. That was never true of the tools I used before.', 'avatar' => null, 'name' => 'Marcus Bell', 'role' => 'Owner, Bell & Co Signage'],
                        ['variant' => 'act', 'icon' => 'ph-paper-plane-tilt', 'label' => 'On the export', 'quote' => 'Everything lands in the CRM we already use. Nobody on the team had to learn a second place to look, which is the only reason it stuck.', 'avatar' => null, 'name' => 'Priya Raman', 'role' => 'Ops manager, Halden Fit'],
                        ['variant' => 'find', 'icon' => 'ph-map-trifold', 'label' => 'On the map', 'quote' => 'Seeing them on a map changed how I plan a week. I work one neighbourhood at a time now instead of driving across the city for two appointments.', 'avatar' => null, 'name' => 'Tomas Lindqvist', 'role' => 'Field sales, Vantage POS'],
                        ['variant' => 'ai', 'icon' => 'ph-sparkle', 'label' => 'On the analysis', 'quote' => 'It tells me what a business is missing before I call. Opening with something specific beats a pitch, and I no longer spend the first minute working out who they are.', 'avatar' => null, 'name' => 'Amara Nwosu', 'role' => 'Founder, Brightline Web'],
                        ['variant' => 'act', 'icon' => 'ph-paper-plane-tilt', 'label' => 'On the credits', 'quote' => 'I pay for what I actually enrich, and a lead with no contact details refunds itself. That was the part I expected to be a catch, and it was not.', 'avatar' => null, 'name' => 'Greg Whitfield', 'role' => 'Director, Whitfield Media'],
                    ],
                ],
            ],
            [
                'name' => 'Homepage Pricing',
                'slug' => 'homepage-pricing',
                'type' => 'homepage_pricing',
                'status' => 'published',
                'description' => 'Pricing plans for the LeadAtlas homepage.',
                'data' => [
                    'eyebrow' => 'Pricing',
                    'title' => 'Pay for the leads, not the seats.',
                    'subtitle' => 'One credit finds and enriches one business. Invite your whole team on any plan — you are billed for what you pull, not for who pulls it.',
                    'plans' => [
                        ['name' => 'Starter', 'price' => '$29', 'period' => '/month', 'credits' => '1,000 credits a month', 'featured' => false, 'badge' => '', 'features' => "Unlimited map searches\nContact enrichment\nAI scoring on every lead\nCSV export", 'button_text' => 'Start free', 'button_link' => '/register'],
                        ['name' => 'Growth', 'price' => '$89', 'period' => '/month', 'credits' => '5,000 credits a month', 'featured' => true, 'badge' => 'Most chosen', 'features' => "Everything in Starter\nAI summaries and drafted emails\nBuilt-in CRM pipeline\nEmail campaigns", 'button_text' => 'Start free', 'button_link' => '/register'],
                        ['name' => 'Scale', 'price' => '$249', 'period' => '/month', 'credits' => '20,000 credits a month', 'featured' => false, 'badge' => '', 'features' => "Everything in Growth\nREST API and webhooks\nBulk export and integrations\nPriority support", 'button_text' => 'Start free', 'button_link' => '/register'],
                    ],
                    'note' => 'Every plan starts with 100 free credits — no card required.',
                    'note_link_text' => 'Compare plans in full',
                    'note_link' => '#pricing',
                ],
            ],
            [
                'name' => 'Homepage FAQ',
                'slug' => 'homepage-faq',
                'type' => 'homepage_faq',
                'status' => 'published',
                'description' => 'FAQ accordion for the LeadAtlas homepage.',
                'data' => [
                    'eyebrow' => 'Questions',
                    'title' => 'Before you spend a credit.',
                    'subtitle' => 'The things people ask before signing up. If yours is not here, ask us directly.',
                    'items' => [
                        ['question' => 'What exactly does one credit pay for?', 'answer' => 'One credit covers one business, end to end — pulling it off the map, following its website for contact details, and running the AI scoring and summary. You are not charged separately for each step, and a search that returns nothing costs nothing.'],
                        ['question' => 'What happens when I run out of credits?', 'answer' => 'Searching stops until the next monthly refill, and nothing is deleted — every lead you have already pulled stays in your account and stays exportable. You can top up at any point without changing plan.'],
                        ['question' => 'How accurate is the AI scoring?', 'answer' => 'Treat it as a ranking, not a verdict. The score is a judgement built from real signals — review volume, site quality, whether online booking exists — and every score shows the reasons behind it, so you can disagree with it on a specific lead. It is there to put the best prospects at the top of a long list, not to decide who you call.'],
                        ['question' => 'Where does the data come from, and is that allowed?', 'answer' => "Business listings come from Google Maps, and contact details come from each business's own public website. It is all publicly listed business information — not personal data and not anything behind a login. You are still responsible for following the outreach rules that apply where you and your prospects are, which is why exports include the source for every field."],
                        ['question' => 'Do I have to use the AI-written emails?', 'answer' => 'No. Every generated line is a draft you can edit, rewrite, or ignore entirely — the leads and their contact details are yours regardless of whether you touch the outreach tools.'],
                        ['question' => 'Can I cancel, and what happens to my leads?', 'answer' => 'Cancel whenever you like, from your account, without emailing anyone. Export everything before your billing period ends and the data is yours to keep — we do not hold your leads hostage to a subscription.'],
                    ],
                ],
            ],
            [
                'name' => 'Homepage Blog',
                'slug' => 'homepage-blog',
                'type' => 'homepage_blog',
                'status' => 'published',
                'description' => 'Featured blog posts for the LeadAtlas homepage.',
                'data' => [
                    'eyebrow' => 'From the blog',
                    'title' => 'How this actually gets done.',
                    'subtitle' => 'Notes on finding local businesses, scoring them, and getting a reply — written for people doing the work.',
                    'posts' => [
                        ['image' => null, 'date_day' => '14', 'date_month' => 'Jul', 'topic' => 'Finding leads', 'variant' => 'find', 'read_minutes' => '7', 'title' => 'A map search is not a lead list. Here is the gap.', 'excerpt' => 'Pulling a hundred businesses off Google Maps takes a morning. Working out which twelve are worth a call takes the rest of the week.', 'author_avatar' => null, 'author_name' => 'Rachel Mendez', 'link' => '#'],
                        ['image' => null, 'date_day' => '08', 'date_month' => 'Jul', 'topic' => 'Scoring', 'variant' => 'ai', 'read_minutes' => '5', 'title' => 'What a lead score should and should not tell you', 'excerpt' => 'A score that cannot explain itself is a horoscope. What to demand of any tool that ranks your prospects.', 'author_avatar' => null, 'author_name' => 'Daniel Osei', 'link' => '#'],
                        ['image' => null, 'date_day' => '02', 'date_month' => 'Jul', 'topic' => 'Outreach', 'variant' => 'act', 'read_minutes' => '6', 'title' => 'The first line decides whether the rest gets read', 'excerpt' => 'Cold email openers that name a specific gap outperform anything built from a template. Some examples, and why.', 'author_avatar' => null, 'author_name' => 'Rachel Mendez', 'link' => '#'],
                    ],
                    'all_articles_text' => 'All articles',
                    'all_articles_link' => '/blog',
                ],
            ],
            [
                'name' => 'Homepage CTA',
                'slug' => 'homepage-cta',
                'type' => 'homepage_cta',
                'status' => 'published',
                'description' => 'Closing call-to-action with search form for the LeadAtlas homepage.',
                'data' => [
                    'eyebrow' => 'Run one now',
                    'title' => 'Every business you want is already on the map.',
                    'keyword_label' => 'What you sell to',
                    'keyword_placeholder' => 'dentists',
                    'location_label' => 'Where',
                    'location_placeholder' => 'Austin, TX',
                    'button_text' => 'Search the map',
                    'form_action' => '/register',
                    'note' => '100 free credits · No card required · Keep every lead you export',
                ],
            ],
            [
                'name' => 'Features Page Hero',
                'slug' => 'features-page-head',
                'type' => 'featurespage_hero',
                'status' => 'published',
                'description' => 'Breadcrumb header for the Features page.',
                'data' => [],
            ],
            [
                'name' => 'Features — Discover Stage',
                'slug' => 'features-stage-discover',
                'type' => 'featurespage_discover',
                'status' => 'published',
                'description' => 'Stage one: discovery features for the Features page.',
                'data' => [
                    'key_icon' => 'ph-fill ph-map-pin',
                    'key_label' => 'Stage one · Discover',
                    'title' => 'Everything Google Maps knows.',
                    'subtitle' => 'You give a keyword and a place. We pull every matching business in that radius, with the details the listing carries.',
                ],
            ],
            [
                'name' => 'Features — AI Layer Stage',
                'slug' => 'features-stage-ai',
                'type' => 'featurespage_layer',
                'status' => 'published',
                'description' => 'Stage two: the AI scoring layer, with a scoring showcase panel.',
                'data' => [
                    'key_icon' => 'ph-fill ph-sparkle',
                    'key_label' => 'Stage two · The AI layer',
                    'title' => 'How the scoring actually works.',
                    'subtitle' => 'A score is not a guess about whether a business is good. It is a judgement about whether your service is worth something to them, built from signals anyone could check by hand — if they had the time.',
                    'items' => [
                        ['icon' => 'ph-article', 'title' => 'Written summaries', 'description' => 'A paragraph on what each business is missing, so you know your angle before you pick up the phone.'],
                        ['icon' => 'ph-pen-nib', 'title' => 'Drafted opening emails', 'description' => 'A first message built around that specific gap. Editable, and never sent without you.'],
                        ['icon' => 'ph-sliders-horizontal', 'title' => 'Tune what counts', 'description' => 'Tell it what you sell and the weighting shifts. A web agency and a supplier do not want the same leads.'],
                    ],
                ],
            ],
            [
                'name' => 'Features — Act Stage',
                'slug' => 'features-stage-act',
                'type' => 'featurespage_act',
                'status' => 'published',
                'description' => 'Stage three: taking the ranked list out of the tool.',
                'data' => [
                    'key_icon' => 'ph ph-paper-plane-tilt',
                    'key_label' => 'Stage three · Act',
                    'title' => 'Then get it out of the tool.',
                    'subtitle' => 'A ranked list is only worth something once it is in front of someone. Take it wherever you already work.',
                    'items' => [
                        ['icon' => 'ph-kanban', 'title' => 'Built-in pipeline', 'description' => 'Move leads through stages, tag them, and log calls without a second tool or an export in between.'],
                        ['icon' => 'ph-envelope-open', 'title' => 'Email campaigns', 'description' => 'Send the drafted openers as a sequence, with replies landing back against the lead.'],
                        ['icon' => 'ph-download-simple', 'title' => 'Export, free', 'description' => 'CSV or XLSX, as many times as you like. Exporting a lead you already hold never costs a credit.'],
                        ['icon' => 'ph-plugs-connected', 'title' => 'REST API and webhooks', 'description' => 'Push new leads straight into your own CRM as they are scored. On the Scale plan.'],
                    ],
                ],
            ],
            [
                'name' => 'Features Page CTA',
                'slug' => 'features-cta',
                'type' => 'featurespage_cta',
                'status' => 'published',
                'description' => 'Closing call-to-action for the Features page.',
                'data' => [],
            ],
            [
                'name' => 'Pricing Page Hero',
                'slug' => 'pricing-page-head',
                'type' => 'featurespage_hero',
                'status' => 'published',
                'description' => 'Breadcrumb header for the Pricing page.',
                'data' => [
                    'title' => 'Pricing',
                    'lead' => 'Pay for the leads, not the seats.',
                ],
            ],
            [
                'name' => 'Pricing — Unit Economics',
                'slug' => 'pricing-unit',
                'type' => 'pricingpage_unit',
                'status' => 'published',
                'description' => 'Hero and "what one credit buys" breakdown for the Pricing page.',
                'data' => [],
            ],
            [
                'name' => 'Pricing — Plans',
                'slug' => 'pricing-plans',
                'type' => 'pricingpage_plans',
                'status' => 'published',
                'description' => 'Plan cards for the Pricing page.',
                'data' => [],
            ],
            [
                'name' => 'Pricing — If You Run Out',
                'slug' => 'pricing-rollover',
                'type' => 'pricingpage_rollover',
                'status' => 'published',
                'description' => 'Rollover, top-up, and data-ownership reassurance cards.',
                'data' => [],
            ],
            [
                'name' => 'Pricing — Compare Table',
                'slug' => 'pricing-compare',
                'type' => 'pricingpage_compare',
                'status' => 'published',
                'description' => 'Feature comparison table across the three plans.',
                'data' => [],
            ],
            [
                'name' => 'Pricing — FAQ',
                'slug' => 'pricing-faq',
                'type' => 'pricingpage_faq',
                'status' => 'published',
                'description' => 'Billing FAQ for the Pricing page.',
                'data' => [],
            ],
            [
                'name' => 'Pricing Page CTA',
                'slug' => 'pricing-cta',
                'type' => 'featurespage_cta',
                'status' => 'published',
                'description' => 'Closing call-to-action for the Pricing page.',
                'data' => [
                    'title' => 'Try it on 100 businesses first.',
                    'body' => 'No card, no trial countdown. Spend the free credits, see what comes back, then pick a plan.',
                    'button_text' => 'Create your account',
                    'button_link' => '/register',
                ],
            ],
            [
                'name' => 'Contact Page Hero',
                'slug' => 'contact-page-head',
                'type' => 'featurespage_hero',
                'status' => 'published',
                'description' => 'Breadcrumb header for the Contact page.',
                'data' => [
                    'title' => 'Contact',
                    'lead' => 'Sales questions, account problems, or a request to be removed from our index — this is the place for all of it.',
                ],
            ],
            [
                'name' => 'Contact — Form & Sidebar',
                'slug' => 'contact-form',
                'type' => 'contactpage_form',
                'status' => 'published',
                'description' => 'Contact form with topic options and the response-times/removal/existing-customer sidebar.',
                'data' => [],
            ],
            [
                'name' => 'Blog Page Hero',
                'slug' => 'blog-page-head',
                'type' => 'featurespage_hero',
                'status' => 'published',
                'description' => 'Breadcrumb header for the Blog page.',
                'data' => [
                    'title' => 'Blog',
                    'lead' => 'Notes on finding local businesses, scoring them, and getting a reply — written for people doing the work.',
                ],
            ],
            [
                'name' => 'Blog — Post Grid',
                'slug' => 'blog-grid',
                'type' => 'blogpage_grid',
                'status' => 'published',
                'description' => 'Category filters, featured article, post grid, and pagination for the Blog page.',
                'data' => [],
            ],
        ];

        foreach ($sections as $section) {
            FrontendSection::updateOrCreate(
                ['slug' => $section['slug']],
                [
                    'name' => $section['name'],
                    'type' => $section['type'],
                    'status' => $section['status'],
                    'description' => $section['description'],
                    'data' => $service->normalizeData($section['type'], $section['data']),
                    'theme_overrides' => [],
                    'preview_image_media_id' => null,
                ]
            );
        }
    }
}
